[package]
name = "native"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "native"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.51"
fib = { path = "../fib" }

